name: proyecto_credibilidad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  - scikit-learn
  - lifelines
  - pymc
  - arviz
  - numba
  - tqdm
  - black
  - pytest
  - pip
  - pip:
    - actuarialmath
    - fitter
    - distfit
    - pingouin
    - plotnine
